[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "monarch-causal-circuits"
version = "0.1.0"
description = "An implementation of monarch causal circuits in pytorch"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
  {name = "Amirsaman Bozorgvar", email = "amirsaman.bozorgvar@stud.tu-darmstadt.de"},
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "torch",
    "networkx",
]

